Imports pbs.Helper.Extensions
Imports pbs.Helper
Imports pbs.BO.Forms

Namespace MetaData

    Public Class ClassField

        Property Index As Integer

#Region "Primary Keys"

        Private _isPrimaryKey As String
        Public Property IsPrimaryKey() As Boolean
            Get
                Return _isPrimaryKey.ToBoolean()
            End Get
            Set(ByVal value As Boolean)
                _isPrimaryKey = If(value, "Y", "N")
            End Set
        End Property

        Private _isAutoGenerated As String
        Public Property IsAutoGenerated() As Boolean
            Get
                Return _isAutoGenerated.ToBoolean()
            End Get
            Set(ByVal value As Boolean)
                _isAutoGenerated = If(value, "Y", "N")
            End Set
        End Property

#End Region

#Region "Types"

        Public Property FieldName As String

        Public Property FieldType As String

        Public Property DBType As String

        Private _defaultValue As String
        Public Property DefaultValue() As String
            Get
                Return _defaultValue
            End Get
            Set(ByVal value As String)
                _defaultValue = value
            End Set
        End Property

        Public Property PropType() As String

        Private _childType As String
        Public Property ChildType() As String
            Get
                Return _childType
            End Get
            Set(ByVal value As String)
                _childType = value
            End Set
        End Property

        Private _isChildCollection As String
        Public Property IsChildCollection() As Boolean
            Get
                Return _isChildCollection.ToBoolean()
            End Get
            Set(ByVal value As Boolean)
                _isChildCollection = If(value, "Y", "N")
            End Set
        End Property

        Private _isReadonly As String
        Public Property IsReadonly() As Boolean
            Get
                Return _isReadonly.ToBoolean()
            End Get
            Set(ByVal value As Boolean)
                _isReadonly = If(value, "Y", "N")
            End Set
        End Property

#End Region

#Region "Attributes"

        Public Property GroupName() As String

        Public Property Tips() As String

        Private _isRequired As String
        Public Property IsRequired() As Boolean
            Get
                Return _isRequired.ToBoolean
            End Get
            Set(ByVal value As Boolean)
                _isRequired = If(value, "Y", "N")
            End Set
        End Property

        Public Property RegexRule As String

        Private _isMergeField As String
        Public Property IsMergeField() As Boolean
            Get
                Return _isMergeField.ToBoolean
            End Get
            Set(ByVal value As Boolean)
                _isMergeField = If(value, "Y", "N")
            End Set
        End Property

        Private _fieldStart As String
        Public Property FieldStart() As String
            Get
                Return _fieldStart
            End Get
            Set(ByVal value As String)
                _fieldStart = value
            End Set
        End Property

        Private _fieldLen As String
        Public Property FieldLen() As String
            Get
                Return _fieldLen
            End Get
            Set(ByVal value As String)
                _fieldLen = value
            End Set
        End Property


        Public Property DatabaseFieldName() As String


        Private _isBrowsable As String = "Y"
        Public Property IsBrowsable() As Boolean
            Get
                Return _isBrowsable.ToBoolean
            End Get
            Set(ByVal value As Boolean)
                _isBrowsable = If(value, "Y", "N")
            End Set
        End Property

        Private _isHidden As String
        Public Property IsHidden() As Boolean
            Get
                Return _isHidden.ToBoolean
            End Get
            Set(ByVal value As Boolean)
                _isHidden = If(value, "Y", "N")
            End Set
        End Property

        Public Property LookupCode As String
        Public Property InputOptions As String
        Public Property ControlType As CtrlType

#End Region

#Region "Constructor"

        Public Sub New(pField As pbs.BO.BusinessRules.ClassField)

            IsPrimaryKey = pField.isPK
            IsAutoGenerated = pField.isIdentity

            FieldName = pField.FieldName
            PropType = pField.FType

            FieldStart = pField.Start
            FieldLen = pField.Len

            IsRequired = pField.Required
            RegexRule = pField.RegexPattern

            IsMergeField = pField.IsMergedField

        End Sub



#End Region

    End Class


End Namespace
